apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-git-listener.fullname" . }}-scripts
  labels:
    {{- include "tekton-git-listener.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "run.sh").AsConfig | indent 2 }}