apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tekton-git-listener.fullname" . }}
  labels:
    {{- include "tekton-git-listener.labels" . | nindent 4 }}
  labels:
    app.kubernetes.io/managed-by: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tekton-git-listener.fullname" . }}
  labels:
    {{- include "tekton-git-listener.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - update
  - patch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tekton-git-listener.fullname" . }}
  labels:
    {{- include "tekton-git-listener.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tekton-git-listener.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tekton-git-listener.fullname" . }}
  namespace: {{ .Release.Namespace }}