apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tekton-git-listener.fullname" . }}-config
  labels:
    {{- include "tekton-git-listener.labels" . | nindent 4 }}
type: Opaque
data:
  repositories.yaml: |
    {{- .Values.config.repositories | toYaml | b64enc | nindent 4 }}
  listeners.yaml: |
    {{- .Values.config.listeners | toYaml | b64enc | nindent 4 }}
